import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'fs';
import path from 'path';

const root = path.resolve('./');

test('style.css contains mobile media queries and canvas responsive rules', () => {
    const css = fs.readFileSync(path.join(root, 'style.css'), 'utf8');
    assert.ok(css.includes('@media (max-width: 900px) and (orientation: landscape)'), 'Missing landscape mobile media query');
    assert.ok(css.includes('@media (max-width: 600px) and (orientation: portrait)'), 'Missing portrait mobile media query');
    assert.ok(css.includes('@media (max-height: 600px) and (orientation: landscape)'), 'Missing low landscape mobile media query');
    assert.ok(css.includes('#game-canvas') || css.includes('canvas'), 'Canvas responsive rules missing');
    assert.ok(css.includes('#info-panel > #turn-indicator.is-white-turn'), 'Compact turn strip white-state style missing');
    assert.ok(css.includes('#info-panel > #turn-indicator.is-dark-turn'), 'Compact turn strip dark-state style missing');
    assert.ok(css.includes('#turn-indicator .turn-dot'), 'Turn strip dot style missing');
    assert.ok(css.includes('#how-to-play-modal'), 'How-to-play modal style missing');
    assert.ok(css.includes('#how-to-play-pages'), 'How-to-play pages container style missing');
    assert.ok(css.includes('#how-to-play-footer'), 'How-to-play footer style missing');
    assert.ok(css.includes('#player-stats-modal'), 'Player stats modal style missing');
    assert.ok(css.includes('#player-stats-cards'), 'Player stats cards style missing');
    assert.ok(css.includes('#player-stats-footer'), 'Player stats footer style missing');
    assert.ok(css.includes('#start-language-container'), 'Start language container style missing');
    assert.ok(css.includes('#start-language-select'), 'Start language select style missing');
    assert.ok(css.includes('#language-select option'), 'Side language option contrast style missing');
    assert.ok(css.includes('#start-language-select option'), 'Start language option contrast style missing');
    assert.ok(css.includes('background-color: #fff8ec'), 'Light option background color missing');
    assert.ok(css.includes('color: #2b1a0e'), 'Dark option text color missing');
    assert.ok(css.includes('#feedback-button-row'), 'Feedback button row style missing');
    assert.ok(css.includes('#feedback-button'), 'Feedback button style missing');
    assert.ok(css.includes('#feedback-modal-card'), 'Feedback modal style missing');
    assert.ok(css.includes('#feedback-modal-links a'), 'Feedback modal link style missing');
    assert.ok(css.includes('#game-feedback-toast'), 'Game feedback toast style missing');
    assert.ok(css.includes('#game-feedback-toast.is-visible'), 'Game feedback toast visibility style missing');
    assert.ok(css.includes('#fullscreen-toggle'), 'Fullscreen toggle style missing');
    assert.ok(css.includes('#auto-bearoff-container'), 'Auto bear-off container style missing');
    assert.ok(css.includes('#auto-bearoff-toggle'), 'Auto bear-off toggle style missing');
    assert.ok(css.includes('body.is-game-fullscreen'), 'Fullscreen body lock style missing');
    assert.ok(css.includes('#game-container.is-focus-mode-root'), 'CSS focus mode root style missing');
    assert.ok(css.includes(':fullscreen') || css.includes('-webkit-full-screen'), 'Native fullscreen selector rules missing');
    assert.ok(css.includes('safe-area-inset-top'), 'Safe-area support missing for fullscreen mode');
    assert.ok(css.includes('scrollbar-gutter: stable both-edges'), 'Scrollbar gutter stabilization missing');
    assert.ok(css.includes('min-height: 100dvh'), 'Dynamic viewport height guard missing');
    assert.ok(css.includes('@media (min-width: 901px) and (max-height: 900px)'), 'Short desktop compaction media query missing');
    assert.ok(css.includes('#info-panel > #turn-indicator.is-white-turn'), 'White turn indicator class style missing');
    assert.ok(css.includes('#info-panel > #turn-indicator.is-dark-turn'), 'Dark turn indicator class style missing');
    assert.ok(css.includes('#auto-bearoff-container'), 'Auto bear-off container layout guard missing');
    assert.ok(css.includes('#auto-bearoff-hint'), 'Auto bear-off hint height guard missing');
});

test('index.html contains rotate notice element, start screen, and restart button', () => {
    const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
    assert.ok(html.includes('id="rotate-notice"'), 'Rotate notice element missing');
    assert.ok(html.includes('id="start-screen"'), 'Start screen overlay missing');
    assert.ok(html.includes('id="start-button"'), 'Start button missing');
    assert.ok(html.includes('id="bot-match-button"'), 'Bot match button missing');
    assert.ok(html.includes('id="friend-match-button"'), 'Friend match button missing');
    assert.ok(html.includes('id="online-match-button"'), 'Online match button missing');
    assert.ok(html.includes('id="start-mode-grid"'), 'Start mode grid missing');
    assert.ok(html.includes('id="start-bot-difficulty"'), 'Start difficulty select missing');
    assert.ok(/id="start-mode-menu"[^>]*role="group"[^>]*aria-labelledby="start-mode-menu-title"/i.test(html), 'Mode menu accessible group missing');
    assert.ok(/id="friend-match-button"[\s\S]*?disabled[\s\S]*?aria-disabled="true"/i.test(html), 'Friend match honest disabled state missing');
    assert.ok(/id="online-match-button"[\s\S]*?disabled[\s\S]*?aria-disabled="true"/i.test(html), 'Online honest disabled state missing');
    assert.ok(html.includes('id="how-to-play-button"'), 'How-to-play button missing');
    assert.ok(html.includes('id="player-stats-button"'), 'Player stats button missing');
    assert.ok(html.includes('id="start-language-container"'), 'Start screen language row missing');
    assert.ok(html.includes('id="start-language-select"'), 'Start screen language select missing');
    assert.ok(/id="start-language-select"[^>]*data-i18n-aria-label="ui.language"/i.test(html), 'Start language select i18n aria label missing');
    assert.ok(/id="start-language-label"[^>]*for="start-language-select"/i.test(html), 'Start language visible label missing');
    assert.ok(html.includes('id="feedback-button"'), 'Feedback button missing');
    assert.ok(html.includes('id="feedback-modal"'), 'Feedback modal missing');
    assert.ok(html.includes('id="feedback-bug-link"'), 'Feedback bug link missing');
    assert.ok(html.includes('id="feedback-feature-link"'), 'Feedback feature link missing');
    assert.ok(/id="feedback-bug-link"[^>]*target="_blank"[^>]*rel="noopener noreferrer"/i.test(html), 'Bug feedback link target/rel missing');
    assert.ok(/id="feedback-feature-link"[^>]*target="_blank"[^>]*rel="noopener noreferrer"/i.test(html), 'Feature feedback link target/rel missing');
    assert.ok(/id="feedback-modal"[^>]*aria-modal="true"/i.test(html), 'Feedback modal aria-modal missing');
    assert.ok(/id="feedback-modal"[^>]*data-i18n-aria-label="ui.feedbackModalLabel"/i.test(html), 'Feedback modal aria-label i18n missing');
    assert.ok(/id="how-to-play-modal"[^>]*aria-modal="true"/i.test(html), 'How-to-play modal aria-modal missing');
    assert.ok(/id="player-stats-modal"[^>]*aria-modal="true"/i.test(html), 'Player stats modal aria-modal missing');
    assert.ok(html.includes('id="guide-prev-button"'), 'Guide previous button missing');
    assert.ok(html.includes('id="guide-next-button"'), 'Guide next button missing');
    assert.ok(html.includes('id="guide-start-button"'), 'Guide start button missing');
    assert.ok(html.includes('id="stats-reset-button"'), 'Stats reset button missing');
    assert.ok(html.includes('id="restart-button"'), 'Restart button missing');
    assert.ok(html.includes('id="die-right-1"'), 'Double move indicator 1 missing');
    assert.ok(html.includes('id="die-right-4"'), 'Double move indicator 4 missing');
    assert.ok(html.includes('id="fullscreen-toggle"'), 'Fullscreen toggle button missing');
    assert.ok(html.includes('id="fullscreen-toggle-label"'), 'Fullscreen visible helper text missing');
    assert.ok(html.includes('id="auto-bearoff-container"'), 'Auto bear-off container missing');
    assert.ok(html.includes('id="auto-bearoff-toggle"'), 'Auto bear-off toggle missing');
    assert.ok(html.includes('id="auto-bearoff-hint"'), 'Auto bear-off accessibility hint missing');
    assert.equal((html.match(/value="champion"/g) || []).length, 2, 'Champion difficulty should exist in both synchronized selectors');
    assert.ok(/<option value="champion" data-i18n="difficulty\.champion">Şampiyon<\/option>/i.test(html), 'Champion difficulty option missing expected value/i18n pairing');
    assert.equal((html.match(/<option value="medium" data-i18n="difficulty\.medium" selected>Orta<\/option>/gi) || []).length, 2, 'Medium difficulty should remain the default in both selectors');
    assert.ok(/id="turn-indicator"[^>]*aria-live="polite"/i.test(html), 'Turn indicator aria-live polite missing');
    assert.ok(html.includes('viewport-fit=cover'), 'Viewport fit meta missing');
    assert.ok(html.includes('id="board-wrapper"'), 'Board wrapper missing for toast attachment');
    assert.ok(html.includes('assets/branding/nardora-splash.css'), 'Nardora splash stylesheet link missing');
    assert.ok(html.includes('mountNardoraSplash'), 'Nardora splash bootstrap script missing');
});
